build-and-publish

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/weave-kubernetes-anywhere/50)

Add support for unversioned tags for default stable kubernetes release

---

docker-images/kubelet-anywhere.sh
docker-images/kubelet-cni/bin/weave-ipam
docker-images/kubelet-cni/bin/weave-net
docker-images/kubelet-cni/net.d/10-weave.conf
docker-images/kubelet.dockerfile
docker-images/toolbox-configure.sh
docker-images/toolbox/resources/docker-compose-v1.2.yml
docker-images/toolbox/resources/skydns-addon-v1.2/controller.yaml
docker-images/toolbox/resources/skydns-addon-v1.2/service.yaml
docker-images/toolbox/resources/skydns-addon/controller.yaml
docker-images/toolbox/scripts/setup-kubelet-volumes

ping https://github.com/weaveworks/weave/issues/1991, https://github.com/weaveworks/weave/issues/1992 and https://github.com/weaveworks/weave/issues/2030
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/weave-kubernetes-anywhere/52)

Add CNI plugin support

---

FIXES.md
README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/weave-kubernetes-anywhere/56)

Top-level docs rewrite

---

DOCKER_FOR_MAC.md
docker-images/toolbox.dockerfile
docker-images/toolbox/resources/docker-compose.yml
docker-images/toolbox/scripts/print-apiproxy-config
docker-images/toolbox/scripts/start-apiproxy

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/kubernetes-anywhere/67)

Add API proxy (close #65)

---

docker-images/apiserver-anywhere.sh
docker-images/apiserver.dockerfile
docker-images/kubelet.dockerfile
docker-images/proxy.dockerfile
docker-images/toolbox.dockerfile
docker-images/toolbox/resources/docker-compose.yml
docker-images/toolbox/scripts/print-local-config

Close #65.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/kubernetes-anywhere/75)

Ditch apiproxy

---

docker-images/toolbox/scripts/create-pki-containers
docker-images/toolbox/scripts/print-secure-localhost-config

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/kubernetes-anywhere/77)

Enable SSH forwarding of the API server

---

build
config
docker-images/kubelet.dockerfile
docker-images/toolbox.dockerfile
docker-images/toolbox/resources/docker-compose.yml
examples/aws-ec2-terraform/secure-v1.2-user-data.yaml
push

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/kubernetes-anywhere/93)

Bump Weave Net version, close #92 and #84

---

docker-images/toolbox-configure.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/kubernetes-anywhere/94)

Turns out `-no-pki` addon flavours never worked

---

docker-images/kubelet-cni/bin/weave-ipam
docker-images/kubelet-cni/bin/weave-net
docker-images/kubelet.dockerfile
test-shellcheck

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/kubernetes-anywhere/98)

Ensure Weave Net CNI wrappers do not defailt to latest tag (close #97)

---

build
config
docker-images/toolbox/resources/docker-compose.yml
push-only-latest-tag
test-shellcheck

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/kubernetes-anywhere/100)

Stronger revision coupling with immutable tags for single-node setup

---

docker-images/kubelet-anywhere.sh
docker-images/toolbox/scripts/setup-kubelet-volumes

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/kubernetes-anywhere/102)

Improve kubelet volumes

---

docker-images/apiserver-anywhere.sh
docker-images/toolbox/scripts/create-pki-containers

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/kubernetes-anywhere/103)

Use `--embed-certs`, few cosmetic tweaks

---

docker-images/toolbox/scripts/create-pki-containers

ping #91
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/kubernetes-anywhere/104)

Take extra SANs as an agrument

---

docker-images/toolbox/scripts/setup-kubelet-volumes
examples/aws-ec2-terraform/networking.tf
examples/aws-ec2-terraform/outputs.tf
examples/aws-ec2-terraform/secure-v1.2-user-data.yaml

Here are some cosmetic changes that were implemented in `test-new-toolbox-in-ec2` branch, and could otherwise get lost.
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/kubernetes-anywhere/105)

Few cosmetic cherry-picks

---

phase1/tf.jsonnet

To work around:
kubernetes/kubernetes#28180
I'm currently testing this.
cc @colemickens

switch tls key algorithm from ECDSA to RSA

---

phase1/azure/azure.json
phase1/azure/azure.jsonnet

I changed a small something in the cloudprovider code I'm about to send a PR for; this is the corresponding change for bring-up.

azure: phase1 add routeTableName to azure.json

---

phase1/azure/azure.json
phase1/azure/azure.jsonnet

Reacting to one more change from the cloudprovider PR.

azure: ad->aad rename

---

phase1/gce/configure-vm.sh
phase2/ignition/Dockerfile
phase2/ignition/do_role
phase2/ignition/vanilla/ignite.jsonnet
phase2/ignition/vanilla/kubelet.service
phase2/ignition/vanilla/manifest/etcd.jsonnet
phase2/ignition/vanilla/manifest/kube-apiserver.jsonnet
phase2/ignition/vanilla/manifest/kube-controller-manager.jsonnet
phase2/ignition/vanilla/manifest/kube-scheduler.jsonnet
phase2/ignition/vanilla/master.jsonnet
phase2/ignition/vanilla/node.jsonnet
phase2/ignition/vanilla/util.jsonnet

It's less than 30mb  and I think we could get it down to 20mb, much faster, and no python dependency on host or master. Requires a slightly modified igntion https://github.com/mikedanese/ignition/tree/vanilla
If I preinstall docker it takes 2.5 minutes to bring up a cluster.
ref #160

prototype: add ignition phase2 for comparison with ansible

---

phase1/gce/configure-vm.sh

This is a build of what is currently in phase2/ignite

bump ignite docker version

---

Dockerfile
Makefile
phase1/azure/Kconfig
phase1/azure/azure.jsonnet
phase1/azure/configure-vm.sh
phase1/azure/do
phase3/do
test/azure/Jenkinsfile
util/validate

This adds a basic Jenkinsfile for testing kubernetes-anywhere (+kubernetes) on Azure.
Currently it builds HEAD of master of `kubernetes` and tests that along with the "current" branch of `kubernetes-anywhere` checked out by the Jenkins job. For now this will be master on a regular interval, with PRs being built on demand and tested as well.
Goal is to provide some basic testing of k-a and kubernetes, and allow me to iterate on some other PRs faster (adding back premium storage, ssd support, isolated deploy dirs).
This actually doesn't work on `master` of Kubernetes due to three issues:
1. (general issue) Problems handling paths with spaces. [PR for this issue.](https://github.com/kubernetes/kubernetes/pull/30583)
2. (recent master regression) [kubelet fails to launch static pods: …

Jenkinsfile for Azure

---

phase3/kube-dns/kube-dns-rc.json

fix dns again

---

Dockerfile
phase1/azure/azure.jsonnet
phase1/gce/gce.jsonnet
phase1/tf.jsonnet

Terraform update with gce fixup

---

Dockerfile
phase1/azure/azure.jsonnet
phase1/tf.jsonnet

This shouldn't be merged unless there's a plan for fixing the other phase1 implementation, since this PR modifies the shared tf jsonnet lib.

Upgrade phase1 (azure) to terraform 0.7.0

---

README.md
phase1/azure/README.md

Rendered form is here: https://github.com/colemickens/kubernetes-anywhere/blob/pr-azure-docs/phase1/azure/README.md
I think this is good for now and I can finally deprecate [azure-kubernetes-demo](https://github.com/colemickens/azure-kubernetes-demo).

Azure Getting Started Guide

---

test/azure/Jenkinsfile

I accidentally broke teardown in my Jenkins jobs. This should fix it.

azure: test: fix teardown

---

phase1/azure/README.md
phase1/azure/create-azure-service-principal.sh

* Add a script to help the user create an Azure Active Directory Service Principal
* Add instructions to docs for using this script
CC: @brendandburns

azure: docs: add AAD SP helper

---

.dockerignore
Dockerfile
Makefile
util/config_to_json
util/docker-build.sh

This stacks on top of #213. Thoughts? Is it worth switching?

Switch base to Alpine

---

phase1/azure/do
util/validate

(I cleaned up the wait message as well)

azure: only tf apply twice if needed

---

phase3/dashboard/dashboard-deployment.json

~~Do not merge. I haven't tested this yet but want to send the PR before I forget about it again.~~
It works fine.

addons: dashboard: 1.4.0-beta.2 -> 1.4.0

---

Makefile

use --rm when running the deploy environment container

---

phase1/azure/README.md

Addresses #234. 
@dcieslak19973, @ahmetalpbalkan: PTAL
Rendered new page is here: https://github.com/colemickens/kubernetes-anywhere/blob/pr-docs-strg-acct-name/phase1/azure/README.md
New section is specifically here: https://github.com/colemickens/kubernetes-anywhere/blob/pr-docs-strg-acct-name/phase1/azure/README.md#cluster-naming-restrictions

azure: document naming restrictions

---

phase1/azure/configure-vm.sh

Fixes #243.
Signed-off-by: Ahmet Alp Balkan <ahmetalpbalkan@gmail.com>

phase1/azure: typo fix for systemd dropin

---

phase1/azure/Kconfig
phase1/azure/do

Fixes #249.
(This stacks on top of PR #248 and should be rebased and merged only after #248 is merged).
cc: @ahmetalpbalkan

azure: always infer tenant_id

---

phase1/azure/do
util/validate

CC: @squillace who reported this as being somewhat confusing.

validate: clarify when success is achieved

---

phase1/azure/README.md

Add some basic troubleshooting directions for Azure.

azure: add troubleshooting directions

---

README.md

Fixed couple of typos in  README.md

Fixed couple of typos in  README.md

---

Makefile
README.md
phase1/Kconfig
phase1/vsphere/Kconfig
phase1/vsphere/README.md
phase1/vsphere/all.jsonnet
phase1/vsphere/configure-vm.sh
phase1/vsphere/do
phase1/vsphere/vSphere.jsonnet
phase1/vsphere/vsphere.conf
phase2/ignition/vanilla/manifest/kube-apiserver.jsonnet
phase2/ignition/vanilla/manifest/kube-controller-manager.jsonnet
phase2/ignition/vanilla/node.jsonnet

This PR adds support for vSphere cloudprovider in kubernetes-anywhere. It is internally reviewed [here](https://github.com/abrarshivani/kubernetes-anywhere/pull/1).

Add support for vSphere cloudprovider

---

phase1/azure/README.md

azure: mention that ACS/ACS-Engine is preferred method

---

phase1/gce/DEVEL.md
phase1/gce/configure-vm-kubeadm.sh
phase1/gce/configure-vm.sh
phase1/gce/do
phase1/gce/gce.jsonnet

Describe the steps for using kubernetes-anywhere to deploy a kubernetes
cluster on GCE VMs with a local development build of kubernetes.

Document GCP development deployment process.

---

phase2/ignition/do_role

Changes ignition provider from vanilla to file and fixes #286.

Change ignition provider from vanilla to file

---

phase1/vsphere/README.md

fixes https://github.com/kubernetes/kubernetes-anywhere/issues/319

Add note for why not to power on template vm

---

phase1/gce/DEVEL.md

Add GCE developer documentation to configure an overlay network and DNS
related pods.

Additional documentation for configuring networking.

---

phase1/gce/do

This loop was trying 60 times, but giving the indication it was only going to try 10.

Make output match reality.

---

phase1/vsphere/vSphere.jsonnet

Fixes #337. 
cc @pdhamdhere @tusharnt @kerneltime @BaluDontu @divyenpatel

vSphere Cloud Provider: Make hostname of VM same as nodename

---

phase1/vsphere/Kconfig
phase1/vsphere/README.md

This PR adds some type checks in Kconfig for vsphere.

Add validation for vsphere

---

phase1/vsphere/README.md

minor grammar fix

---

phase1/Kconfig

Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>

Change default nodes to 3 to suit trial size GCE account

---

phase1/Kconfig
phase1/gce/do
phase2/Kconfig

This is a simple pr to fix-up the comments left out in #429.
/assign @pipejakob

Follow-up pr to fix comments in #429

---

phase1/vsphere/README.md

Updating K8S-Anywhere Getting Started Guide for vSphere based on the Menu Option changes made in the PR: https://github.com/kubernetes/kubernetes-anywhere/pull/437
Issue: https://github.com/vmware/kubernetes/issues/249
Summary of changes:
- In the instruction for running deployment container mounted local /tmp directory so that kubeconfig.json file can be copied to the local machine easily.
- Updated Menu Options and briefly describe each menu
- Added OVA for vSphere 5.5
- In cnastorage/kubernetes-anywhere image made vsphere as default provider.
New Image is uploaded at `cnastorage/kubernetes-anywhere:08252017`
Once this PR is approved, I will tag `cnastorage/kubernetes-anywhere:08252017` to `cnastorage/kubernetes-anywhere:latest`
Please review: @rohitjogvmw, @BaluDontu, @tusharnt, …

Updating Kubernetes-Anywhere getting started guide for vSphere

---

phase1/gce/configure-vm-kubeadm.sh
phase1/gce/configure-vm.sh
phase1/gce/gce.jsonnet
phase3/Kconfig
phase3/all.jsonnet
phase3/flannel/flannel-cluster-role-binding.json
phase3/flannel/flannel-config-map.json
phase3/flannel/flannel-daemon-set.json
phase3/flannel/flannel-service-account.json
phase3/flannel/flannel.jsonnet

Add flannel

---

Makefile
phase1/do
phase1/gce/configure-vm-kubeadm.sh
phase1/gce/do
phase1/vsphere/do
phase2/Kconfig
phase2/ignition/do
phase2/kubeadm/do

Issue #431 
Adds structure for upgrades and fills in the upgrade implementation for kubeadm on gce.
Design doc: https://docs.google.com/a/google.com/document/d/1PoDeqD8qu1KbAd-fb7xOVB1G7YTyD6VLLlhaVB3QeA4/edit?usp=sharing

Add upgrade logic to kubernetes anywhere

---

phase1/vsphere/README.md

Fixes https://github.com/vmware/kubernetes/issues/399

Fix typos in vSphere README

---

phase1/vsphere/README.md

- Fixed the ordering of the questions
- Fixed some extra whitespace
Signed-off-by: JJ Asghar <jj@chef.io>

Updated the vSphere readme for the new make config

---

phase2/kubeadm/configure-vm-kubeadm-master.sh

Refs kubernetes/kubernetes#66338
kubeadm 1.11 needs v1alpha2, thus we should use `config migrate`
to update the configration file. this should also work for future
versions, as long as `config migrate` works.
kubeadm 1.10.x would not trow an error.
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-selfhosting/537/artifacts/e2e-537-f2b95-master/serial-1.log
```
Jul 19 19:33:35 e2e-537-f2b95-master startup-script: INFO startup-script: your configuration file uses an old API spec: "kubeadm.k8s.io/v1alpha1". Please use kubeadm v1.11 instead and run 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
Jul 19 19:33:35 e2e-537-f2b95-master startup-script: INFO startup-script: …
```

phase2: use the v1alpha2 kubeadm config if needed 

---

phase1/vsphere/README.md

Typo fix: specifed->specified
