kubernetes/kubernetes-anywhere

examples/docker-machine/create-cluster.sh

Fixes typo in `create-cluster.sh` for Docker Machine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/kubernetes-anywhere/58)

Fixes typo in create-cluster.sh

---

docker-images/toolbox/scripts/setup-single-node

Fixes #73, I think.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/kubernetes-anywhere/76)

make setup-single-node more robust when pki images have been deleted

---

.travis.yml
build
build-and-push
config
push
test-shellcheck

NO_PUSH and NO_BUILD are unintuitive, and didn't seem to work for me (leading me to accidentally push to docker hub. This seems safer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/weaveworks/kubernetes-anywhere/80)

Split build-and-push into 2 separate scripts

---

phase1/google-compute-engine/provision.sh

`git.io` supports HTTPS, and `provision.sh` should use it. Otherwise, it would be trivial for an attacker to launch a man-in-the-middle (MITM) attack against the machine running the script. Since the files being downloaded are executed by the same script promptly thereafter, this is a very easy way for an attacker to achieve remote code execution on the machine running the script.
Fixes #130.

Use HTTPS to download executables in provision.sh

---

phase1/gce/lib/gce.jsonnet

This change makes terraform apply print the master IP at the end of the output.
cc @mikedanese

Output master IP.

---

Dockerfile
Makefile
phase1/Kconfig
phase1/azure/Kconfig
phase1/azure/all.jsonnet
phase1/azure/azure.json
phase1/azure/azure.jsonnet
phase1/azure/configure-vm.sh
phase1/azure/do
phase2/Kconfig
phase2/ansible/Makefile
phase2/ansible/playbooks/roles/master/templates/etcd.jsonnet
phase2/ansible/playbooks/roles/master/templates/kube-apiserver.jsonnet
phase2/ansible/playbooks/roles/master/templates/kube-controller-manager.jsonnet
phase2/ansible/playbooks/roles/master/templates/kube-scheduler.jsonnet
phase2/ansible/playbooks/roles/node/tasks/main.yml
phase2/ansible/playbooks/roles/node/templates/kubelet.service.j2
util/config_to_json

Of the remaining issues in [the closed min-turnup PR](https://github.com/kubernetes/kube-deploy/pull/106):
1. "terraform resource names": I still punted on this. I've started to a couple times, but it's a rather surprisingly large amount of extra changes/text with unclear benefit to me. In terms of enabling side-by-side deployments, it seems there are other problems to sort out. (Comparing to the GCE one, it looks like GCE is going to hit the same "multiple resources with same name" error due to the TLS/kubeconfig assets not being named uniquely per-`instance_prefix`.) I still think it'd be better to support multiple clusters by having entirely separate directories per-cluster. With their own separate `tfstate`s, `kubeconfig`s, etc.
2. "prefer jsonnet": I've added the Azure cloud config …

Azure: Phase1 Implementation + necessary Phase2 Changes

---

.travis.yml
Makefile
util/config_to_json

For some reason current version has thrown this when I tried running
make in a container:
```
docker build .
...
> docker run 8d0b7ef3b34c
make config
make[1]: Entering directory '/root/kubernetes-anywhere'
mkdir -p .tmp; curl -sSL --fail -o ".tmp/conf" \
"https://storage.googleapis.com/public-mikedanese-k8s/kconfig/4.6/linux/conf"; \
chmod +x ".tmp/conf"
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
/bin/sh: 2:     "https://storage.googleapis.com/public-mikedanese-k8s/kconfig/4.6/linux/conf"; \: not found
/bin/sh: 3: chmod +x ".tmp/conf": not found
Makefile:26: recipe for target '.tmp/conf' failed
make[1]: *** [.tmp/conf] Error 127
make[1]: Leaving directory '/root/kubernetes-anywhere'
make: *** [default] Error 2
Makefile:23: recipe for target …
```

Few improvements to Kconfig bits

---

phase2/ansible/playbooks/roles/node/templates/kubelet.service.j2

Partially addresses #162.
This allows EFK to work. Without this no container logs are picked up.

fix kubelet mounts for logging

---

phase1/gce/gce.jsonnet

cc @mikedanese @errordeveloper

Use the same node suffix everywhere, these are used by service controller.

---

phase2/ansible/playbooks/roles/node/templates/kubelet.service.j2

Mount the /dev directory in the kubelet container so that it can detect persistent disks.

---

phase1/gce/Kconfig
phase1/gce/gce.jsonnet

Let the user create and delete the network. Default network usually exists.
Temporarily address https://github.com/kubernetes/kubernetes-anywhere/issues/141
@madhusudancs WDYT?

don't manage the gce network with tf

---

phase3/kube-dns/kube-dns-rc.json
phase3/kube-dns/kube-dns-svc.json

I believe this fixes the failing DNS e2e tests. Note that this value matches the --cluster-dns kubelet parameter https://github.com/kubernetes/kubernetes-anywhere/blob/master/phase2/ignition/vanilla/node.jsonnet#L23
Testing now.

fix failing dns e2e tests

---

test/azure/Jenkinsfile

Deployments keep getting stuck. Either something is up with Azure networking or the Google storage bucket where `kubectl` is pulled from. If ignition fails to download `kubectl` it seems to fail out, and `kubelet.service` never gets created.
The pipeline then gets stuck waiting. For now, I'm adding the timeout in the Jenkins pipeline.

azure: test: add timeout waiting for cluster

---

Makefile
phase1/azure/do
phase1/gce/do
test/azure/Jenkinsfile
util/validate

Note:
* I updated the string that `phase1/<provider>/do` expects to look for `{deploy,destroy}-cluster` to align with the target in the top-level `Makefile`. The functions inside `./do` that they map to are still just `deploy`/`destroy`.

`make deploy` now waits for cluster and deploys addons

---

Makefile
phase1/azure/Kconfig
phase1/azure/README.md
phase1/azure/create-azure-service-principal.sh
phase1/azure/do
phase2/Kconfig
util/docker-build.sh

The PR does a few things:
1. Fixes a small bug in `Makefile` introduced when I rearranged the `make deploy` command.
2. Upgrades `terraform`, adds `curl` to the docker environment, removes a defunct comment.
3. Rearranges the Azure phase1 `Kconfig` so the user can input `subscription_id` first off and then spam `<enter>` for all the other questions.
4. Changes the defaults in phase2 to point to an ignition container that I'm updating and to point to the latest `1.4.0-alpha.3` build of Kube 1.4.x.
5. **Automatic** creation of a service principal for Azure. This changes the `create-azure-service-principal.sh` script in a few ways:
* (`do`)  Will notice that the `tenant_id` field is empty and will automatically infer it based on the `subscription_id`.
* (`do`)  Will notice that the …

Azure: Automatically provision Service Principal for user

---

phase1/azure/README.md

The instructions were a bit off and had the user creating `~/.kube/config` as a directory, which resulted in the move placing the edit into a directory such that the file ended up at `~/.kube/config/kubeconfig.json` rather than at `~/.kube/confifg`.
CC: @anhowe This is the issue you mentioned this afternoon.

azure: fix kubeconfig mkdir instructions

---

phase1/azure/do

`./create-azure-service-principal.sh` is meant to fix propagation issues, but it only fixes it for the RBAC Role Assignment.
As it turns out, this same problem can occur if Terraform fires up too quickly after the role assignment. For now, the best I can do is introduce a sleep and hope that's sufficient.
If 10 seconds isn't enough, users can simply re-execute `make deploy` and it should eventually succeed.
This stacks on top of #224 .

azure: fix another SP propagtion delay

---

phase1/azure/do

1. Had accidentally hard-coded my subscription ID, meaning all users would've gotten the MS tenant ID if they were using the automatic SP creation script. No information risk, but it wouldn't have worked for them.
2. The backfilling of the config files wasn't being done correctly, causing the user to need to run `make deploy` twice.
Both of these issues are resolved with this PR.

azure: fix tenant_id auto-detection and back-filling

---

phase2/Kconfig
phase3/heapster/heapster-deployment.json
phase3/kube-dns/kube-dns-deployment.json
phase3/kube-proxy/kube-proxy-ds.jsonnet
util/docker-build.sh

1. Phase2: Default to `1.4.0` final.
2. Addons: DNS: Mirror upstream changes
3. Addons: Kube-Proxy: Remove deprecated flag
4. Addons: Kube-Proxy: kubeconfig volume should be read-only
5. Addons: Heapster: switch to `1.2.0` final.

Update kubernetes, heapster, kube-proxy, kube-dns

---

phase1/azure/README.md
phase1/azure/do

1. Wait 30 seconds instead of 10 to workaround AAD propagation delays.
2. Document this failure case and workaround.

azure: extend wait for AAD consistency

---

phase1/azure/Kconfig
phase1/azure/azure.jsonnet
phase1/azure/do

1. Add a `storage_name` parameter to `phase1/azure/Kconfig`.
2. Use this field in the Azure Terraform file.
3. In `phase1/azure/do` check, and auto-fill-if-missing the `storage_account_name` similarly to how the TenantID and SP are auto-generated and filled in.
Not terribly pretty, but functional for now and would enable us to remove the "global uniqueness" requirement as it's been a source of confusion.
Please take a look @ahmetalpbalkan, @ggm-at-apnic and let me know what your feedback is.

azure: add storage_name param, autogen if blank

---

phase2/ignition/vanilla/kubelet.service

The mounting of `/var/log` enables necessary log sharing when Fluentd is in play.

[kubelet.service] Add the mounting of /var/log.

---

Makefile

As a consumer of kubernetes-anywhere, I wanted a supported way to discover the `kubeconfig.json` file path without relying on the internal details of where it's stored per phase1 provider.
The target name feels a little awkward, so I'm open to suggestions of a better one.
CC @mikedanese

New make target: kubeconfig-path

---

phase1/gce/gce.jsonnet

This matches what azure does, and the expectations of the Makefile.
After this change, doing `make deploy` is fixed for GCE, since `util/validate` is able to find the correct configuration to connect and count the nodes.
See https://github.com/kubernetes/kubernetes-anywhere/issues/271
CC @mikedanese

Fixes #271: Output GCE's kubeconfig.json to .tmp

---

phase1/gce/configure-vm-ignition.sh
phase1/gce/configure-vm-kubeadm.sh
phase1/gce/configure-vm.sh
phase1/gce/do
phase1/gce/gce.jsonnet
phase2/Kconfig

Currently, this only supports using the most recent .deb packages.
- Exposes port 9898 internally for discovery service
- Nodes use master's internal IP
- Move a lot of configure-vm.sh logic into phase2 provider dirs (which get concatenated by jsonnet)
CC @mikedanese

Add kubeadm support for phase2.

---

phase1/gce/do

This is already implemented in the azure phase1, and will allow users to automate destruction without interactive prompts:
$ make FORCE_DESTROY=y destroy
This change is built on top of another pull request (https://github.com/kubernetes/kubernetes-anywhere/pull/270) so please only look at the newest commit.
CC @mikedanese

Support FORCE_DESTROY option in gce.

---

phase1/gce/configure-vm-kubeadm.sh

`Kubeadm` now defaults to 6443 for the secure API listener, so override it to match the conventions of the rest of `kubernetes-anywhere`.
CC @mikedanese

Force API port 443 to match other implementations.

---

phase1/gce/configure-vm-kubeadm.sh

A race condition in one of `kubeadm`'s preflight checks has been causing occasional failures of masters/nodes to come up correctly.
Since we provide a completely automated setup, any failed preflight checks don't offer much value since the user isn't interacting with `kubeadm` to see its error messages and address the issues, so we should
disable them anyway.
CC @mikedanese

Skip kubeadm preflight checks.

---

phase1/gce/do

When using `kubeadm` for phase2, the TLS certs created by `terraform` are ignored, and `kubeadm init` generates these on the master. If the user wants to be able to connect to the cluster remotely, we need to fetch the kubeconfig from the master once it's ready:
$ make WAIT_FOR_KUBECONFIG=y deploy-cluster
CC @mikedanese

Add option to fetch kubeconfig from kubeadm master.

---

phase1/gce/configure-vm-kubeadm.sh
phase1/gce/gce.jsonnet

This allows `kubeadm init` to include the master's external IP as part of the TLS certificate. Otherwise, remote clients reject the certificate since it doesn't match the IP they're connecting to.
CC @mikedanese

Specify master's external IP via --api-advertise-addresses.

---

phase1/vsphere/README.md
phase2/ignition/vanilla/kubelet.service

In vSphere CloudProvider, when node restarts, kubelet doesn't start. This PR fixes the same.

Fix: Kubelet restarts for vSphere CloudProvider

---

phase2/ignition/vanilla/node.jsonnet

This PR removes cidr parameters for vsphere. Since vSphere supports flannel these parameters are not needed.

Remove cidr parameters for vsphere

---

phase1/vsphere/Kconfig
phase1/vsphere/vSphere.jsonnet

Currently kube-anywhere doesn't work with multiple resource pools. Consider the below scenario:
I have a VC deployed with multiple clusters and hence multiple resource pools. I deployed the "KubernetesAnywhereTemplatePhotonOS" in one of the ESX boxes present in one of the clusters.
when I did make deploy, kube-anywhere fails to deploy and reports the following errors.
Error applying plan:
2 error(s) occurred:
* vsphere_virtual_machine.kubevm2: default resource pool resolves to multiple instances, please specify
* vsphere_virtual_machine.kubevm1: default resource pool resolves to multiple instances, please specify
Right now kube-anywhere doesn't take into consideration the resource pools as a config parameter that must provided to the user to be entered. This is in contrast with kube-up …

kube-anywhere doesn't work with multiple resource pools in vSphere

---

phase1/gce/configure-vm-kubeadm.sh
phase1/gce/gce.jsonnet
phase2/Kconfig

Instead of only supporting the latest stable release, allow specifying a Cloud Storage link for pulling arbitary builds. This should allow developers to bring up kubeadm clusters using their local development build, as well as help e2e test kubeadm on pull requests or master commits.
CC @mikedanese

Add support for gs:// links for kubeadm .debs.

---

util/docker-build.sh

The `menuconfig` target was broken because `kconfig-mconf` was missing from the Docker image, and `kconfig-mconf` wasn't being compiled because `ncurses-dev` wasn't detected. Adding `ncurses-dev` enables compiling of both `mconf` and `nconf`, but we need to disable `nconf` because it depends on `libgpm`, which is missing from the Alpine repo.
After this change, running `make docker-dev` followed by `make menuconfig` from within the Docker shell works.
CC @jcbsmpsn

Fix "make menuconfig" from within "make docker-dev"

---

phase1/vsphere/README.md
phase2/Kconfig

Changes for the issue - https://github.com/vmware/kubernetes/issues/54
@kerneltime @BaluDontu Updated phase1/vsphere/README.md and phase2/Kconfig to recommend kubernetes 1.4.8 for vSphere Cloud Provider

Updated documentation to recommend kubernetes 1.4.8 for vSphere Cloud Provider

---

phase1/gce/configure-vm-kubeadm.sh
phase1/gce/do

The kubeadm command was updated to do input validation on
the token used for initializing and joining clusters. This update
generates lowercase tokens to match the kubeadm input rules.

Use lowercase hex token for kubeadm commands.

---

phase1/vsphere/vSphere.jsonnet

Kubernetes-anywhere scripts were writing vsphere.conf after launching of ignition container which created race condition between vSphere.conf and apiserver. This PR fixes that.
Fixes this error,
```
Feb 14 15:05:16 photon-zv1KbtvMG docker[626]: F0214 15:05:16.854753     709 plugins.go:80] Couldn't open cloud provider configuration /etc/kubernetes/vsphere.conf: &os.PathError{
Op:"open", Path:"/etc/kubernetes/vsphere.conf", Err:0x2}
```

Writing vsphere conf before launching ignition container

---

phase1/vsphere/README.md
phase2/Kconfig

Updated documentation and `phase2/Kconfig `to recommend kubernetes 1.5.3 for vSphere Cloud Provider
cc: @kerneltime @abrarshivani @BaluDontu @tusharnt @pdhamdhere

Updated documentation to recommend kubernetes 1.5.3 for vSphere Cloud Provider

---

phase2/ignition/vanilla/manifest/etcd.jsonnet
phase2/ignition/vanilla/manifest/kube-apiserver.jsonnet
phase2/ignition/vanilla/node.jsonnet

This PR adds parameter default storage backend to apiserver as etcd2. While launching k8s-cluster with kubernetes master branch (commit d82e51e) using kubernetes-anywhere. I found that kubernetes api-server fails with an error
```
E0111 03:00:53.829193   29597 status.go:62] apiserver received an error that is not an metav1.Status: rpc error: code = 13 desc = transport is closing
…
logging error output: "k8s\x00\n\f\n\x02v1\x12\x06Status\x12F\n\x04\n\x00\x12\x00\x12\aFailure\x1a0rpc error: code = 13 desc = transport is closing\"\x000\xf4\x03\x1a\x00\"\x00"
```
Currently, etcd3 is made as default storage backend for api-server and kubernetes-anywhere uses etcd2. Hence, this error occurs. This can be resolved by adding parameter ```storage-backend=etcd2``` to apiserver manifest.
Refer this: …

Add default storage backend as etcd3

---

phase1/vsphere/README.md
phase1/vsphere/configure-vm.sh
phase2/Kconfig
phase2/ignition/Dockerfile
phase2/ignition/vanilla/master.jsonnet

For vSphere cloud provider kubectl was downloaded in phase1 since downloading in phase2 using ignition gave an [error](https://github.com/kubernetes/kubernetes-anywhere/issues/286). Now, that is [fixed](https://github.com/kubernetes/kubernetes-anywhere/pull/305) this PR removes the downloading of kubectl from phase1 of vSphere Cloud Provider. Also, kubectl downloaded in phase2 was of v1.3.4 even though kubernetes cluster launched was of different version. This PR fixes that.
@mikedanese Can you please build the static binary and update at https://storage.googleapis.com/public-mikedanese-k8s/k8s/ignition? Also, I tested with master branch of ignition it fails therefore can you build binary for commit 6ff90ec7f985d783246fc429ea.

Move kubectl download to phase2 for vSphere CloudProvider

---

phase1/vsphere/README.md

On vSphere instructions, the dashboard is running in http, not https.

vSphere: The proxy to the Kubernetes API server is http

---

phase1/vsphere/do

Currently Kube-anywhere installs 1.4.0 kubectl binary inside the container spawned by using "make docker-dev" for any kubernetes cluster deployments either it be 1.4.7, 1.4.8, 1.5.2 or 1.5.3.
So there needs to be a better way to download the specific version of kubectl based on the Kubernetes cluster the user wants to deploy. For example, if the user deployed v1.5.3 kubernetes cluster, the container needs to have a kubectl v1.5.3 binary working in place. If the user deployed v1.4.8 kubernetes cluster, the container needs to have a kubectl v1.4.8 binary working in place..
Also, there needs to be a way where the kubectl binary for a specific version can be used if it is already downloaded rather than downloading it again every time.
The fix for this PR will handle the above mentioned 2 …

Download right version of kubectl binary

---

phase1/vsphere/README.md

Fixes #https://github.com/vmware/kubernetes/issues/100. This PR adds latest OVA timestamp in README for vSphere. Latest OVA add network dependency in flannel systemd unit.
Tested:
Created kubernetes cluster of v1.5.3. Run ```echo "" > /etc/machine-id``` and **restart** node.
Earlier:
flannel initially failed due to network interface not available and started after docker. This is why dashboard didn't worked.
With this change,
flannel don't fail initially. Now, dashboard works.
//cc @kerneltime

Add latest OVA timestamp in README for vSphere

---

phase1/vsphere/do

while deploying kubernetes cluster user can specify hyperkube version from docker registry as below.
```
docker registry (phase2.docker_registry) [gcr.io/google-containers] (NEW) gcr.io/google-containers
kubernetes version (phase2.kubernetes_version) [v1.5.3] (NEW) v1.5.3
```
but when user is using custom hyperkube image from private repository - `https://hub.docker.com/r/divyen/hyperkube-amd64/tags/` for example as below
```
docker registry (phase2.docker_registry) [gcr.io/google-containers] (NEW) docker.io/divyen
kubernetes version (phase2.kubernetes_version) [v1.5.3] (NEW) nightly-1.5
```
kubernete-anywhere will try to download kubelet from `https://storage.googleapis.com/kubernetes-release/release/nightly-1.5/bin/linux/amd64/kubectl` which is not the right URL.
to avoid failing …

skip downloading kubelet if URL is not accessible

---

Makefile

For some reason, this was breaking the multiline `if` used in the kubeconfig-path target under different versions of make/bash. Removing these quotes fixed the kubeconfig-path make target in the docker-dev shell.

Remove unnecessary quoting of SHELLFLAGS.

---

phase1/gce/configure-vm-kubeadm.sh
phase1/gce/do

- The `--discovery` flag has reverted back to `--token`
- Token strings are back to `<6>.<16>` instead of `<6>:<16>`
- `--api-advertise-addresses` is now `--apiserver-advertise-address`
- `--api-port` is now `--apiserver-bind-port`
- `--use-kubernetes-version` is now `--kubernetes-version`
CC @luxas @mikedanese

Accommodate upstream kubeadm CLI changes.

---

util/docker-build.sh

This provides the `gcloud` CLI, which is very useful when creating GCE clusters, and is also a requirement if `WAIT_FOR_KUBECONFIG` is set when using `kubeadm` as the phase2 provider.

Add Google Cloud SDK to Docker image.

---

phase1/gce/do

This was a silly mistake in 02dddef. If the very first line was `STARTFILE`, then the entire file was getting truncated. Using `0` instead of `1` for the range matching allows the match to occur on the first line, giving the intended behavior if nothing else comes before `STARTFILE`.

Fix sed command.

---

phase3/Kconfig
phase3/all.jsonnet
phase3/weave-net/weave-net-cluster-role-binding.json
phase3/weave-net/weave-net-cluster-role.json
phase3/weave-net/weave-net-daemon-set.json
phase3/weave-net/weave-net-service-account.json
phase3/weave-net/weave-net.jsonnet
util/docker-build.sh

Most likely, this addon will only be used by clusters using `kubeadm` for phase2 that require a CNI provider.
The json files were generated by fetching https://git.io/weave-kube-1.6 (which is multidoc yaml), breaking it apart into individual documents, and converting them to json.
Since `ClusterRole` and `ClusterRoleBinding` weren't supported by the older `kubectl` used in the Docker image, I also bumped its version.
CC @mikedanese

Add support for weave-net addon.

---

phase3/all.jsonnet

When running `make config` or `make menuconfig`, options that are disabled don't necessarily go into .config with values of `n`. In some versions of kconfig-frontends, like the one in this repo's Docker image, comments get stored instead:
Without this change, attempting to run `make addons` or even just `phase3/do gen` chokes on these values, since jsonnet can't find configuration for them. With the change, it treats addons omitted from .config as disabled.
This should also help upgrade-proof clients that automate the creation of .config, so upstream additions of new addons don't render old .config files broken.

Allow disabled addons to be omitted from .config

---

phase2/ignition/vanilla/manifest/etcd.jsonnet
phase2/ignition/vanilla/manifest/kube-apiserver.jsonnet

With the ignition image having` etcd:3.0.4`, we have observed issue, volume can not be detached from the node after pod is deleted. 
This issue is producible on Kubernetes Release **v1.5.3**,  which is working fine with `etcd:2.2.1`.
Issue is verified with creating two ignition images, and using same Kubernetes releases - 1.5.3
> divyen/ignition.etcd-3.0.4:v1 - disk never get detached from node VM, after pod is deleted.
> divyen/ignition.etcd-2.2.1:v1 - disk get detached from the node VM, after pod is deleted.
@tusharnt @BaluDontu @abrarshivani

phase2 - ignition - reverting etcd-container image back to  etcd:2.2.1

---

phase1/vsphere/README.md

Adding minimal privileges required for kubernetes-Anywhere.
Verified privileges on vCenter 6.5 with deploying Kubernetes 1.5.3 cluster using Kubernetes-Anywhere master branch.
Performed following operations
Create Storage Class, Create PVC, Create POD, Delete POD, Delete Volume.
Verified Disk attach/detach volume create/delete is working fine with these set of privileges.
CC: @abrarshivani @BaluDontu @luomiao @tusharnt @pdhamdhere @kerneltime

Adding minimal privileges required for kubernetes-Anywhere

---

phase1/vsphere/README.md

Recommending  user to download tagged release instead of `git clone https://github.com/kubernetes/kubernetes-anywhere repository`
Informing user about not to install `weave-net` add on.
cc: @tusharnt @BaluDontu @abrarshivani

Updating vsphere/README.md

---

phase1/gce/configure-vm-kubeadm.sh

When using our bazel-generated .debs, kubelet had previously been silently started by `kubeadm init` itself (even with preflight checks disabled), which https://github.com/kubernetes/kubernetes/pull/45231 fixed.
With that behavior gone, we need to enable/start kubelet explicitly.
https://github.com/kubernetes/kubeadm/issues/268

Enable/start kubelet in kubeadm phase2.

---

phase1/gce/configure-vm-kubeadm.sh

This is important for some of our e2e tests to be able to exercise the default behavior of omitting this parameter.

Don't add --kubernetes-version if the value is empty.

---

phase1/gce/configure-vm.sh

I found that this step was required when testing with a Debian image (debian-8-jessie-v20170426), and it's also one the steps in the [kubeadm getting started guide](https://kubernetes.io/docs/getting-started-guides/kubeadm/).
This doesn't actually allow the Debian image to be used end-to-end, since there are still dependency conflicts with the Docker package, but it does allow the startup to get a little further.

In GCE, make sure apt-transport-https is installed.

---

phase1/gce/gce.jsonnet
phase1/tf.jsonnet
util/docker-build.sh

This updates the Terraform version used by project from 0.7.2 to 0.9.4. It fixes multiple issues related to Terraform (see : https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md). 
- As the cert request flow changed after the 0.7.5 version, the jsonnet had to be updated to reflect this change. 
- The env variable TERRAFORM_SHA256SUM was also deleted from the docker-build script as it wasn't used.

Update terraform to 0.9.4

---

util/docker-build.sh

Untarring with verbose produces hundreds of lines of output which seems a bit unnecessary and makes it harder to process what the scripts are doing for newcomers.

Turn off verbose output for untar

---

phase1/vsphere/README.md
phase2/Kconfig
phase2/ignition/vanilla/manifest/etcd.jsonnet

Updating `phase1/vsphere/README.md` for Kubernetes v1.6.5 recommendation.
1.6.5 change log
- vSphere cloud provider: Report same Node IP as both internal and external. (#45201, @abrarshivani)
- vSphere cloud provider: Filter out IPV6 node addresses. (#45181, @BaluDontu)
- vSphere cloud provider: Remove the dependency of login information on worker nodes for vsphere cloud provider. (#43545, @luomiao)
- vSphere cloud provider: Fix volume detach on node failure. (#45569, @divyenpatel)
- vSphere cloud provider: Fix fetching of VM UUID on Ubuntu 16.04 and Fedora. (#45311, @divyenpatel)
README.md Preview is available at https://github.com/divyenpatel/kubernetes-anywhere/blob/30413563ee5c91d2949715ed5e44cf7c041ba7bd/phase1/vsphere/README.md
PR Changes:
- Recommending v1.6.5
- Provided steps to …

Updating `phase1/vsphere/README.md` for Kubernetes v1.6.5 recommendation

---

phase1/vsphere/Kconfig
phase1/vsphere/vSphere.jsonnet

Fixes: https://github.com/kubernetes/kubernetes-anywhere/issues/422
Currently Kubernetes-Anywhere asks user to specify the name of the cluster and then uses this name to create vm folder on the root. Node VMs are then placed on this folder.
Customer requested to prompt menu option to specify VM folder path where cluster needs to be deployed.
This PR addressed above customer request.
**New menu options looks like as below.**
`VM Folder name or Path (e.g kubernetes, VMFolder1/dev-cluster, VMFolder1/Test Group1/test-cluster) (phase1.vSphere.vmfolderpath) [kubernetes] (NEW) divyen/kubernetes`
**Testing:**
`.phase1.vSphere.vmfolderpath="divyenp/kubernetes/Test Cluster"`
In this case 
VM Folders divyenp and sub folders were not present, folder structure is created by kubernetes-anywhere and …

Allow user to specify VM folder Path where Node VMs needs to be placed

---

Makefile
phase1/azure/README.md
phase1/azure/azure.jsonnet
phase1/azure/do
phase1/gce/README.md
phase1/gce/do
phase1/gce/gce.jsonnet
phase1/vsphere/README.md
phase1/vsphere/do
phase1/vsphere/vSphere.jsonnet
phase2/Kconfig
phase3/do
test/azure/Jenkinsfile
util/docker-build.sh

This PR enables deploying multiple clusters from the same workspace without affecting each other.
- .tmp directory is moved to a directory with name <cluster_name>
- kubeconfig.json is stored in <cluster_name> directory instead of .tmp directory.
We could bring-up multiple clusters with the changes in this PR sequentially, bringing them up in parallel needs some more modifications.
This is done as part of effort to migrate federation cluster bring-up method to k8s-anywhere   Ref: https://github.com/kubernetes/test-infra/issues/3858
The environment supposed to be used in test-infra is `gce+kubeadm+weavenet` and this PR has been tested in this environment.
The other 2 environments azure and vsphere has not been tested, but are minor changes and can be reviewed.
/assign @pipejakob 
/assign …

Deploy multiple clusters from same workspace

---

phase1/gce/gce.jsonnet

`gce.jsonnet` was recently refactored to skip elements that aren't needed based on the `phase2.provider`. However, based on jsonnet's parsing, the second of the two `if` statements was being appending to the `else { }` block of the previous `if`, and so it was being short-circuited entirely instead of independently evaluated.
The intent of the code was to logically do:
if condition1 {
append(X)
}
if condition2 {
append(Y)
}
but based on jsonnet's list append binding, it was actually doing:
if condition1 {
append(X)
}
else if condition2 {
append(Y)
}
Since `condition1` and `condition2` are identical here, rather than two separate `if`s I've merged them into a single one. I've tested to ensure that in the case of ignition, both the `null_resource` and TLS resources are included, and in the …

Fix binding of TLS resources for ignition.

---

phase1/gce/do

If a field is completely missing, then this invocation prints out the string `null`:
$ echo $(jq -r '.phase1.ssh_user' .config.json)
The result is that our `if [[ -n "$VAR" ]]` checks will actually see the string `null` instead of an empty string.
Piping the query through the "values" filter will filter out null values and produce the desired empty output, which fixes the conditionals:
$ echo $(jq -r '.phase1.ssh_user | values' .config.json)

Fix jq handling of missing fields.

---

phase1/gce/do

If the .config file is missing `phase1.ssh_user`, we should still attempt to explicitly use `$USER@host` to avoid the poorly documented default behavior of gcloud looking up the user from the service account (which is wrong, in prow's case):
https://github.com/kubernetes/kubeadm/issues/219
If `$USER` is unset, like it is in the `make docker-dev` environment, then we can still fall back to omitting the `user@` portion of the ssh command. But, this will make it a little friendlier to use in other environments.

If phase1.ssh_user isn't set, also try to use $USER.

---

Makefile
util/validate

Current implementation fails to check if node is in ready condition after deployment.
To fix the issue, the validate script is updated to check for both cluster-readiness and node-readiness.
/assign @pipejakob 
/cc @luxas

Fix validate for node readiness

---

phase1/gce/configure-vm-kubeadm.sh
phase1/gce/gce.jsonnet
phase2/Kconfig

Prior to this change, the kubelet on the master and nodes would always be at the same version as kubeadm. Breaking the version of the kubelet away from the version of kubeadm gives the flexibility of starting up consistent clusters that are at an older version than the kubeadm binary.
This helps with e2e testing issues: https://github.com/kubernetes/kubeadm/issues/431
Configuration could be updated to reflect their purpose a bit better eg. kubernetes_version really is the control plane version. Such naming changes are outside the scope of this pull request to focus efforts on fixing things.

Allow configuration for a kublet version that differs from kubeadm

---

phase1/gce/configure-vm-kubeadm.sh
phase2/kubeadm/do

If a kubeadm gs version is provided with a backslash, the gsutil cp command will try and fail to pull a file path with a double backslash (ie. gs util gs://kubernetes-release-dev/bazel/v1.8.0-beta.1/bin/linux/amd64//kubeadm). Trim trailing backslashes on kubeadm gs versions to handle this problem.

Handle a kubeadm gs version with a trailing slash by trimming the slash.

---

Makefile
phase1/vsphere/vSphere.jsonnet

1. This PR fixes #370 i.e with this fix: kubernetes-anywhere will accept '%' char in password for vSphere.
2. Currently, if user executes ```make clean``` and config file doesn't exist then phase1 folder is deleted. This PR also fixes this issue.

Fix for vSphere password and make clean

---

phase1/gce/configure-vm-kubeadm.sh
phase1/gce/gce.jsonnet
phase2/Kconfig
phase2/kubeadm/do
phase3/Kconfig
phase3/all.jsonnet
phase3/gce-storage-class/storage-class.json
phase3/gce-storage-class/storage-class.jsonnet

This PR is in continuation to migrate deployment mechanism used by federation to k8s-anywhere as listed out in https://github.com/kubernetes/test-infra/issues/3858. This is the 5th task in that series.
Federation CI jobs needs k8s clusters deployed with cloud-provider enabled for load-balancer type services and persistent volumes.
/cc @luxas @pipejakob @madhusudancs @kubernetes/sig-federation-pr-reviews

Enable cloud-provider in GCE based deployments.

---

phase1/gce/configure-vm.sh
phase1/gce/gce.jsonnet
phase1/openstack/configure-vm.sh
phase1/openstack/openstack.jsonnet
phase2/Kconfig
phase2/kubeadm/configure-vm-kubeadm-master.sh

added kube-proxy mode in kubeadm config file, so that we can easily chose proxy mode when build cluster, espically if we want use ipvs mode. 
Already added kube-proxy-mode args in kubeadm, in [this pr](https://github.com/kubernetes/kubernetes/pull/53962) : https://github.com/kubernetes/kubernetes/pull/53962

add kube-proxy mode in kubeadm config file

---

phase1/gce/Kconfig
phase2/Kconfig

Partly addresses the concerns raised in https://github.com/kubernetes/kubernetes-anywhere/issues/487
Bumped the default kubernetes version to v1.8.4, which is the current stable version supported.
/assign @pipejakob

Improve couple of Kconfig tems

---

phase1/gce/configure-vm.sh
phase1/gce/gce.jsonnet
phase1/openstack/configure-vm.sh
phase1/openstack/openstack.jsonnet
phase2/Kconfig
phase2/kubeadm/configure-vm-kubeadm-master.sh

allow option 'FeatureGates' when deploying kubeadm on the master's node of the cluster.
this option when set with "CoreDNS=true" allow to run CoreDNS as the default DNS server in the cluster instead of usual kube-dns
Adds part of e2e integration requires for CoreDNS that is an ALPHA feature added to kubeadm 
See: kubernetes/kubeadm#446
it will need a second part in the project "test-infra"
_In order to have the deployment of cluster run on GCE, I needed to fix issues on "terraform" tool usage (command line and config file). see gce/do and gce/gce.jsonnet_
**rollbacked in last commit. That was tied to the version of "terraform" used for testing.**

add featuregate opt for kubeadm

---

phase2/kubeadm/configure-vm-kubeadm-master.sh

The Kubernetes ci-kubernetes-e2e-kubeadm-gce-ipvs CI tests are failing (see [gubernator results](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-ipvs) ) in the kubernetes-anywhere Phase 2.
The kube master serial logs show YAML decode errors for kubeadm config where either a '{' or newline is expected afer "featureGates:". The [kubeadm config file documentation](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#config-file) indicates that the expected format for featureGates is:
```
featureGates:
<feature>: <bool>
<feature>: <bool>
```
Accordingly, the config in the startup script needs to be changed from:
```
featureGates: SupportIPVSProxyMode=true
```
to:
```
featureGates:
SupportIPVSProxyMode: true
```
Fixes #527

Add newline before IPVS featureGates config in startup

---

Makefile

Closes issue #493 
Makefile as noted in above issue is designed to force 'make config' when .config is missing.
Additionally changed all ${} variable references to $() for consistency.

Force run of 'make config'

---

phase2/kubeadm/configure-vm-kubeadm.sh

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-cni-flannel/3157/artifacts/e2e-3157-098af-master/serial-1.log
INFO startup-script:  kubeadm depends on cri-tools (>= 1.11.0); however:
INFO startup-script:   Package cri-tools is not installed.
INFO startup-script: dpkg: error processing package kubeadm (--install):
INFO startup-script: Removing kubeadm (1.12.0~alpha.0.1584+aa06ec6dd3a010) ...
...
INFO startup-script: kubeadm init --skip-preflight-checks --config $KUBEADM_CONFIG_FILE
INFO startup-script: + kubeadm init --skip-preflight-checks --config /etc/kubeadm/kubeadm.yaml
INFO startup-script: /startup-wsmbtznt/tmpjucy96_3: line 211: kubeadm: command not found
INFO startup-script: Return code 127.
INFO Finished running startup scripts.
@thockin …

kubeadm requires cri-tools

---

OWNERS

add me and @fabriziopandini to the OWNER files for this branch.
the repo now has `/lgtm` and `/approve` commands enabled and we should use them:
https://github.com/kubernetes/kubernetes-anywhere/issues/563

update OWNERS file for branch kubeadm-e2e

---

Makefile
phase1/gce/do
phase2/kubeadm/configure-vm-kubeadm.sh

from the discussion on slack:
> echo the .config.json at the beginning of the build-log.txt, it will be simpler to reproduce the failing case.
the second commit adds ac check if the kubeconfig is emtpy....
for some reason `gcloud ssh` gets it like that and i have no idea why.
at least that's some indication of something being wrong with the config.
third change is to ignore pre-release packages for `stable` kubelet.
/kind cleanup
/assign @fabriziopandini

apply a set of patches to build scripts and Makefile

---

phase2/kubeadm/configure-vm-kubeadm-master.sh

The decision on which kubeadm configuration type to use
should not happen based on the version from a k8s endpoint,
but rather based on the version of the client (kubeadm binary).
xref: https://github.com/kubernetes/kubernetes/issues/70375
/priority critical-urgent
/kind bug
/assign @fabriziopandini

kubeadm: decide on config type based on kubeadm client version

---

phase1/gce/configure-vm.sh

this PR bumped the minimum docker version in the kubelet and turned our e2e tests red:
https://github.com/kubernetes/kubernetes/pull/72831
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce-master/1519
i have tested the change in a xenial container.
/assign @fabriziopandini 
/cc @timothysc @mauilion

phase1: bump docker version to 1.13.1

---

phase2/kubeadm/do

@fabriziopandini as promised, but i haven't experimented if this fixes it.
do we have to still include this for 1.11?

phase2: exclude the 'config upload' step for upgrades
